const test=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
function setup(){const select={value:'causal-v1',disabled:true};const ctx={window:{addEventListener(){},ldProductionCategory:'disaster'},document:{getElementById:id=>id==='narrativeFormat'?select:null}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'ld-story-format.js'),'utf8'),ctx);return {ctx,select,policy:ctx.window.LDStoryFormat};}
test('legacy and unknown formats stay original, with byte-identical prompt output',()=>{const {ctx,policy}=setup();for(const value of [undefined,null,'original','unknown']){ctx.window.ldNarrativeFormat=policy.normalize(value);assert.equal(policy.label(value),'Original LD');assert.equal(policy.decorate('Approved original prompt','P5','shorts'),'Approved original prompt');}});
test('trial adds distinct progression guidance while leaving hook and cards intact',()=>{const {ctx,policy}=setup();ctx.window.ldNarrativeFormat='causal-v1';const guards=Array.from({length:14},(_,i)=>policy.guidance('P'+(i+1),'shorts'));assert.equal(new Set(guards).size,14);for(const guard of guards){assert.match(guard,/Event-specific facts/);assert.match(guard,/Preserve duration/);}for(const stage of ['HOOK','ENDING','THUMBNAIL'])assert.equal(policy.decorate('locked',stage,'shorts'),'locked');assert.match(policy.guidance('S20','longform'),/longform/);ctx.window.ldProductionCategory='drama';assert.equal(policy.decorate('fiction','P2','shorts'),'fiction');});
test('new project unlocks selector and clears cross-project approval memory',()=>{const {ctx,select,policy}=setup();ctx.window.ldApprovedMemory={stages:{P1:{done:true}}};policy.reset();assert.equal(select.value,'original');assert.equal(select.disabled,false);assert.equal(ctx.window.ldApprovedMemory,null);});
test('same title projects with different story formats have separate identity',()=>{const source=fs.readFileSync(path.join(root,'project-library.js'),'utf8');const fn=source.match(/function sameProjectIdentity\(project,state\)\{[\s\S]*?\n  \}/)[0];const context={};vm.createContext(context);vm.runInContext(fn,context);const old={topic:'Same disaster',format:'shorts'};assert.equal(context.sameProjectIdentity({state:old}, {...old,narrativeFormat:'original'}),true);assert.equal(context.sameProjectIdentity({state:old}, {...old,narrativeFormat:'causal-v1'}),false);});
test('collectState persists story format for backups and project reopening',()=>{const source=fs.readFileSync(path.join(root,'app.js'),'utf8');const fn=source.split('\n').find(x=>x.startsWith('function collectState()'));const context={window:{ldNarrativeFormat:'causal-v1'},stagesEl:{querySelectorAll:()=>[]},storyPremiseEl:null,storyBibleEl:null,projectTitle:{textContent:'Trial'},formatEl:{value:'shorts'}};vm.createContext(context);vm.runInContext(fn,context);const restored=JSON.parse(JSON.stringify(context.collectState()));assert.equal(restored.narrativeFormat,'causal-v1');assert.equal(restored.topic,'Trial');});
