import test from 'node:test';
import assert from 'node:assert/strict';
import {classifyTopic,buildResearch} from '../api/ai-research.js';
import {validateResearch,expandResearch,curatedNarration} from '../api/narration-research.js';
const topic='Mount Tambora Eruption — Indonesia — 1815';
const urls=['https://volcano.si.edu/volcano.cfm?vn=264040','https://www.usgs.gov/test-tambora'];
function fixture(){return {status:'completed',usage:{input_tokens:100,output_tokens:100},output:[{type:'web_search_call',action:{type:'search',sources:urls.map(url=>({url}))}}],output_text:JSON.stringify({eventMatch:true,year:1815,location:'Sumbawa',identitySources:urls,claims:['HOOK',...Array.from({length:14},(_,i)=>'P'+(i+1))].map((stage,i)=>({stage,kind:i<2?'identity':'development',claim:'Distinct fixture fact '+i,support:'Fixture source support '+i,sourceUrl:urls[i%2],disputed:false}))})};}
test('routes major disaster families independently',()=>{for(const [t,k] of [['Tambora Eruption','volcano'],['Cyclone Nargis','cyclone'],['China Floods','flood'],['Haiti Earthquake','earthquake'],['Sanriku Tsunami','tsunami'],['Tri-State Tornado','tornado'],['Wellington Avalanche','avalanche'],['Peshtigo Fire','fire']])assert.equal(classifyTopic(t),k);});
test('Tambora has no curated coverage: confirms initial failure mechanism',async()=>{const r=await buildResearch(topic);assert.equal(r.hazardType,'volcano');assert.equal(r.narrationGate.allowed,false);assert.equal(curatedNarration(topic),false);});
test('accepts distinct stage evidence from retrieved independent sources',()=>{const r=validateResearch(fixture(),topic);assert.equal(Object.keys(r.stageMap).length,15);assert.equal(r.narrationGate.exactNumbersAllowed,false);});
test('rejects fabricated URLs, wrong year, duplicate filler and missing stages',()=>{for(const change of [p=>p.year=1816,p=>p.identitySources=['https://evil.test','https://fake.test'],p=>p.claims.pop(),p=>p.claims[5].claim=p.claims[4].claim,p=>p.claims[7].kind='identity']){const f=fixture(),p=JSON.parse(f.output_text);change(p);f.output_text=JSON.stringify(p);assert.throws(()=>validateResearch(f,topic));}});
test('one request researches then reuses successful cache without added usage',async()=>{let calls=0,usage=0;const base={validation:{status:'NEEDS_REVIEW'}};const opts={apiKey:'test',fetchImpl:async()=>{calls++;return {ok:true,json:async()=>fixture()}},onUsage:u=>{usage+=u.estimatedCostUsd}};assert.equal((await expandResearch(topic,base,opts)).narrationGate.allowed,true);assert.equal((await expandResearch(topic,base,opts)).researchExpansion,'cached');assert.equal(calls,1);assert(usage>=.01);});
test('conflicts never bypass the gate and errors are not cached',async()=>{let calls=0;const opts={apiKey:'test',fetchImpl:async()=>{calls++;throw new Error('network down')}};const conflict={validation:{status:'CONFLICT'},narrationGate:{allowed:false}};assert.equal(await expandResearch('Conflict 1900',conflict,opts),conflict);assert.equal(calls,0);for(let i=0;i<2;i++)assert.equal((await expandResearch('Unknown event 1901',{validation:{status:'NEEDS_REVIEW'}},opts)).narrationGate.allowed,false);assert.equal(calls,2);});
